adminUser:
  password: vault:lionsugar/adminUser:password
  username: admin
dashboardAuthID: vault:lionsugar:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:lionsugar:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:lionsugar/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:lionsugar/prow:hmacToken
